site_name: FrontISTR ver. 5.0
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - fortran

use_directory_urls: false

nav:
- ホーム: index.md
- チュートリアル:
    - 静解析（弾性）: 04_tutorial/tutorial_01.md
    - 静解析（弾性、並列）: 04_tutorial/tutorial_02.md
    - 静解析（超弾性１）: 04_tutorial/tutorial_03.md
    - 静解析（超弾性２）: 04_tutorial/tutorial_04.md
    - 静解析（弾塑性１）: 04_tutorial/tutorial_05.md
    - 静解析（弾塑性２）: 04_tutorial/tutorial_06.md
    - 静解析（粘弾性）: 04_tutorial/tutorial_07.md
    - 静解析（クリープ）: 04_tutorial/tutorial_08.md
    - 接触解析（１）: 04_tutorial/tutorial_09.md
    - 接触解析（２）: 04_tutorial/tutorial_10.md
    - 接触解析（３）: 04_tutorial/tutorial_11.md
    - 線形動解析: 04_tutorial/tutorial_12.md
    - 非線形動解析: 04_tutorial/tutorial_13.md
    - 非線形接触動解析: 04_tutorial/tutorial_14.md
    - 固有値解析: 04_tutorial/tutorial_15.md
    - 熱伝導解析: 04_tutorial/tutorial_16.md
    - 周波数応答解析: 04_tutorial/tutorial_17.md
- 例題:
    - 単純形状モデルによる検証: 05_example/example_01.md
    - 弾性静解析用実モデル例題: 05_example/example_02.md
    - 固有値解析用実モデル例題: 05_example/example_03.md
    - 熱伝導解析用実モデル例題: 05_example/example_04.md
    - 線形動的解析用実モデル例題: 05_example/example_05.md
