site_name: FrontISTR ver. 5.0
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - fortran

use_directory_urls: false

nav:
- HOME: index.md
- Installation:
    - Required software: 01_install/install_01.md
    - Extracting the Archive File: 01_install/install_02.md
    - Installation: 01_install/install_03.md
    - Installation using cmake: 01_install/install_04.md
    - Editing Makefile.conf: 01_install/install_05.md
    - List of Makefile.conf Variables: 01_install/install_06.md
- Appendix:
    - Installation procedure to CentOS7.3(cmake): 01_install/install_07.md
    - Installation procedure to CentOS7.3(Makefile.conf): 01_install/install_08.md
    - Installation procedure to Ubuntu16.04(cmake): 01_install/install_09.md
    - Installation procedure to Ubuntu16.04(Makefile.conf): 01_install/install_10.md
    - Installation procedure to Windows10(Makefile.conf): 01_install/install_11.md
