variables:
  REGISTRY: registry.gitlab.com/frontistr-commons/frontistr_manual

image: ${REGISTRY}/build:latest

cache:
  paths:
    - markdown_files/ja/site
    - markdown_files/en/site

stages:
  - build
  - deploy

mkdocs:
  stage: build
  script:
    - cd markdown_files/ja
      #    - python ../numbering.py
    - mkdocs build
    - cd ../en
      #    - python ../numbering.py
    - mkdocs build
    - cd ../pdf_scripts
    - ./mdtopdf.sh
  artifacts:
    paths:
    - markdown_files

pages:
  stage: deploy
  only:
    - master
  script:
    - mkdir -p public
    - cp -r markdown_files/ja/site public/$CI_COMMIT_TAG/ja
    - cp -r markdown_files/en/site public/$CI_COMMIT_TAG/en
  artifacts:
    paths:
    - public
