site_name: FrontISTR ver. 5.0
theme: 
    name: 'bootstrap'
use_directory_urls: false

pages:
- HOME: index.md
- Overview:
    - Quick Start guide: index.md
- Manuals:
    - Installation manual: index.md
    - Finite Element Method Analysis Theory: index.md
    - User's manual: index.md
    - Tutorial: index.md
- Release note: A1_release_note/00_release_note.md
- Cheat sheet: A2_cheat_sheet/00_cheat_sheet.md
