site_name: FrontISTR ver. 5.0
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - fortran

use_directory_urls: false

nav:
- Finite Element Method Analysis Theory: index.md
- Static Analysis:
  - Infinitesimal Deformation Linear Elasticity Static Analysis: ./02_theory/theory_01.md
  - Nonlinear Static Analysis Method: ./02_theory/theory_02.md
- Dynamic Analysis:
  - Dynamic Analysis Method: ./02_theory/theory_03.md
  - Eigenvalue Analysis: ./02_theory/theory_05.md
  - Frequency Response Analysis: ./02_theory/theory_06.md
- Heat Conduction Analysis: ./02_theory/theory_04.md
- References: ./02_theory/theory_07.md

