site_name: FrontISTR ver. 5.0
theme: bootstrap
use_directory_urls: false

pages:
- ホーム: index.md
- 概要:
    - クイックスタートガイド: index.md
- マニュアル:
    - インストールマニュアル: index.md
    - 理論マニュアル: index.md
    - 解析マニュアル: index.md
    - チュートリアル: index.md
- リリースノート: A1_release_note/00_release_note.md
- チートシート: A2_cheat_sheet/00_cheat_sheet.md
