site_name: FrontISTR ver. 5.0
theme: bootstrap
use_directory_urls: false

pages:
- ホーム: index.md
- 解析の流れ: ./03_analysis/analysis_01.md
- 入力ファイル:
    - 全体制御データ (hecmw_ctrl.dat): ./03_analysis/analysis_02.md
    - 領域分割制御データ (hecmw_ctrl_part.dat): ./03_analysis/analysis_03.md
    - メッシュデータ (mesh.msh): ./03_analysis/analysis_04.md
    - 解析制御データ (mesh.cnt): ./03_analysis/analysis_05.md
    - 可視化制御データ (hecmw_vis.ini): ./03_analysis/analysis_05.md
- 出力ファイル:
    - ログデータ: ./03_analysis/analysis_05.md
    - リザルトデータ (mesh.res): ./03_analysis/analysis_05.md
    - リスタートデータ (mesh.restart): ./03_analysis/analysis_05.md
    - 可視化データ: ./03_analysis/analysis_05.md
- 要素リスト: ./03_analysis/analysis_06.md
- 材料リスト: ./03_analysis/analysis_07.md
- ユーザーサブルーチン: ./03_analysis/analysis_08.md
