site_name: FrontISTR ver. 5.0
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - fortran

use_directory_urls: false

nav:
- HOME: index.md
- Tutorial:
    - Static Analysis (Elasticity) : 04_tutorial/tutorial_01.md
    - Static Analysis (Elasticity, Parallel) : 04_tutorial/tutorial_02.md
    - Static Analysis (Hyperelasticity Part 1) : 04_tutorial/tutorial_03.md
    - Static Analysis (Hyperelasticity Part 2) : 04_tutorial/tutorial_04.md
    - Static Analysis (Elastoplasticity Part 1) : 04_tutorial/tutorial_05.md
    - Static Analysis (Elastoplasticity Part 2) : 04_tutorial/tutorial_06.md
    - Static Analysis (Viscoelasticity) : 04_tutorial/tutorial_07.md
    - Static Analysis (Creep) : 04_tutorial/tutorial_08.md
    - Contact Analysis (Part 1) : 04_tutorial/tutorial_09.md
    - Contact Analysis (Part 2) : 04_tutorial/tutorial_10.md
    - Contact Analysis (Part 3) : 04_tutorial/tutorial_11.md
    - Linear Dynamic Analysis : 04_tutorial/tutorial_12.md
    - Nonlinear Dynamic Analysis : 04_tutorial/tutorial_13.md
    - Nonlinear Contact Dynamic Analysis : 04_tutorial/tutorial_14.md
    - Eigenvalue Analysis : 04_tutorial/tutorial_15.md
    - Heat Conduction Analysis : 04_tutorial/tutorial_16.md
    - Frequency Response Analysis: 04_tutorial/tutorial_17.md
- Example Verification:
    - Verification by Simple Geometric Model: 05_example/example_01.md
    - Example of Acutual Model for Elastic Static Analysis: 05_example/example_02.md
    - Example of Actual Model for Eigenvalue Analysis: 05_example/example_03.md
    - Example of Actual Model for Heat Conduction Analysis: 05_example/example_04.md
    - Example of Actual Model for Linear Dynamic Analysis: 05_example/example_05.md
